# Use the official Node.js LTS image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Copy the rest of your application code
COPY . .


RUN npm run build

# Expose port 3000
EXPOSE 3000


# ENV NODE_ENV=production

CMD ["npm", "run", "start"]
