# Generated by Django 4.2.16 on 2025-02-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_notification_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='conversation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
