# Generated by Django 4.2.16 on 2025-02-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notification_conversation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='conversation_id',
        ),
    ]
